### ISSUE TITLE
Mobile UI

### ISSUE THREAD

**Issue by dhigham** [resolvetosavelives/healthicons#110]
Love the icons so far.

It would be really useful to have matching UI icons for a medical app. So things like: settings, tools, accessories, upload, send, more and reload.

**Comment by dburka** [comment]
Interesting. We were just debating this as a team yesterday. There are open source icons like Remixicon.com and Feathericons.com that have many mobile UI elements. Are you looking for a more consistent set with the rest of the icons in HealthIcons?

**Comment by dhigham** [comment]
Hi

Absolutely that! I’m working on an app and they would be useful. Also the pills and meds section is great, how about bottles as in the small ones vitamins would come in.

Love what you’re doing BTW. 🙏

Dan

Sent from my iPhone

On 29 Jun 2021, at 19:40, Daniel Burka ***@***.******@***.***>> wrote:


Interesting. We were just debating this as a team yesterday. There are open source icons like Remixicon.com<http://Remixicon.com> and Feathericons.com<http://Feathericons.com> that have many mobile UI elements. Are you looking for a more consistent set with the rest of the icons in HealthIcons?

**Comment by dburka** [comment]
On it Dan. Thanks! Might take a few months... but we're on it.

**Comment by dburka** [comment]
I added a few to the upcoming new icons list. What's missing that you'd include? @dhigham 
<img width="545" alt="image" src="https://user-images.githubusercontent.com/711809/124362479-f2a9a880-dbe9-11eb-81ed-93dba3f200ee.png">
