### ISSUE TITLE
Icon Request: [types of cancers / more body parts / human organs]

### ISSUE THREAD

**Issue by marialyv** [resolvetosavelives/healthicons#111]
**Describe the icon you'd like to see and how you would use it.**
Hey everyone -- Congrats on HealthIcons! What a great effort. I see so many awesome icons already. I've got a few more icons I'd love to see available for use. They are for popular types of cancers, which are really just various body parts / human organs with a tumor/cancer growth. Check out the list below and feel free to contact me directly if you want additional help with direction or a link to a presentation I'm making that incorporates these icons :-) Thanks a lot! Maria

Bladder
https://www.dreamstime.com/bladder-cancer-line-icon-linear-style-sign-mobile-concept-web-design-tumor-outline-vector-symbol-logo-illustration-image173675929
https://www.canstockphoto.com/urinary-bladder-with-tumors-line-icon-80404910.html
https://www.vectorstock.com/royalty-free-vector/urinary-bladder-with-tumors-line-icon-bladder-vector-30798747

Breast
https://www.123rf.com/photo_55481421_stock-vector-line-icon-skin-cancer-icon.html

Colorectal
https://www.dreamstime.com/bowel-cancer-line-black-icon-oncology-isolated-vector-element-outline-pictogram-web-page-mobile-app-promo-bowel-cancer-line-image180323255

Esophagus
https://www.dreamstime.com/esophageal-cancer-line-icon-esophageal-cancer-line-icon-linear-style-sign-mobile-concept-web-design-esophageal-tumor-image173675872

Gastric
https://www.123rf.com/photo_140976831_stock-vector-stomach-cancer-line-icon-linear-style-sign-for-mobile-concept-and-web-design-stomach-ulcer-outline-v.html

Gynecologic - you guys have done this more/less (Cervical Cancer)

Lung - you guys have done this more/less (Tuberculosis)

Lymphatic System
https://www.flaticon.com/premium-icon/lymph-nodes_3323127
https://www.dreamstime.com/lymph-nodes-concept-lymphatic-system-human-ducts-logo-icon-clinic-hospital-medical-poster-anatomical-banner-education-image207469351

Pancreatic
https://www.vectorstock.com/royalty-free-vector/pancreas-with-tumors-line-icon-pancreatic-cancer-vector-30799195

Prostate
https://www.flaticon.com/free-icon/prostate_4349178
https://www.canstockphoto.com/prostate-cancer-concept-88375388.html

Skin
https://depositphotos.com/243597286/stock-illustration-skin-cancer-linear-icon-thin.html

Stomach
https://www.123rf.com/photo_140976831_stock-vector-stomach-cancer-line-icon-linear-style-sign-for-mobile-concept-and-web-design-stomach-ulcer-outline-v.html

Thyroid
https://thenounproject.com/search/?q=thyroid&i=945148
https://thenounproject.com/term/thyroid/2996621/

Others:
Cell nuclei, cancerous
https://thenounproject.com/term/cancer/91287/

Tissue 
https://biorender.com/icon/lab-and-objects/wells-plates-and-cultures/tissue-sample-2/

Biopsy
https://drive.google.com/file/d/1skE67J6X3hohlqIzG6GaJh6h3sOBaRgU/view?usp=sharing

Urine
https://thenounproject.com/term/urine-test/2835120/
https://www.vectorstock.com/royalty-free-vectors/urine-sample-icon-vectors

Biomarker
https://medium.com/a-microbiome-scientist-at-large/science-in-plain-language-what-is-a-biomarker-ad42b78b4c47
https://uploads-ssl.webflow.com/5bb4fef7124bc13e4e2679b7/5bd08156c6fe93c5a2aef043_icon-025-bimarkerdiscovery.svg 
https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSNHdDBmA5JGoCP2fZjaz9Gi8REIe3vzRJTniZ_AZYH8-2Qi_rg4pcZyddxYrJ0T45D5k&usqp=CAU

Generic/basic patient - you guys have underweight and overweight patient

Test tubes - you guys have an individual test tube
https://drive.google.com/file/d/151ckcMlqyoOL0hd2F0CAeBqw0mRAVVuJ/view?usp=sharing
https://thenounproject.com/term/test-tubes/736464/

Tumor
https://biorender.com/icon/cell-types/generic-cells/tumor-cellular-editable-02/

Microscope w specimen
https://thenounproject.com/term/biology/2060123/
https://drive.google.com/file/d/1CEONq4eXkbI3zV1AT7gRcw5NNBsBF285/view?usp=sharing

Diagnostics
https://drive.google.com/file/d/1pEQWwhfuBTc0d8Tat-azU4f-nD2jwERO/view?usp=sharing

Risk Analysis
https://drive.google.com/file/d/1BVx1p7J0noFNiPjlgkI6dyA9eTdVb3-Q/view?usp=sharing

Chord Diagram
https://thenounproject.com/search/?q=chord+diagram&i=2797261

**Comment by dburka** [comment]
Holy smokes. These are GREAT @marialyv !!!!

**Comment by dburka** [comment]
@marialyv ... for the body parts... are you asking for `Bladder Cancer` or `Bladder`? We can, of course, do both. Also, for cancer, is it better to show abnormal cells or to show the "ribbon" icon we used for Cervical Cancer?

<img width="377" alt="image" src="https://user-images.githubusercontent.com/711809/124347810-522c9780-db9b-11eb-91de-d23d5799c5ab.png">

**Comment by SamanvithaAN** [comment]
Hey @marialyv. Currently, we've added the below icons. Rest are on the way! Thanks for being patient with us.
- Pancreatic Cancer
- Prostate Cancer
- Stomach Cancer
- Cell Nuclei Cancerous
- Cell Nuclei

**Comment by dburka** [comment]
We've added quite a few of these by now @marialyv . I'm going to mark as closed for now. Thanks for your patience!
