### ISSUE TITLE
Errors in few icons

### ISSUE THREAD

**Issue by cyberalien** [resolvetosavelives/healthicons#113]
Few icons are not 48x48:

public/icons/svg/filled/symbols/paved_road_alt.svg is 49 x 49
public/icons/svg/negative/symbols/paved_road.svg is 49 x 49
public/icons/svg/negative/symbols/running_water_alt.svg is 49 x 49
public/icons/svg/outline/people/mental_disorders.svg is 47 x 48
public/icons/svg/outline/symbols/breeding_sites.svg is 49 x 48
public/icons/svg/outline/symbols/paved_road_alt.svg is 49 x 49

Also few icons have white boxes, which I suspect should not be there because they are not present in other icons:

public/icons/svg/filled/blood/blood_a_n.svg
public/icons/svg/filled/blood/blood_a_p.svg
public/icons/svg/filled/blood/blood_ab_n.svg
public/icons/svg/filled/blood/blood_ab_p.svg
public/icons/svg/filled/blood/blood_b_n.svg
public/icons/svg/filled/blood/blood_b_p.svg
public/icons/svg/filled/blood/blood_o_n.svg
public/icons/svg/filled/blood/blood_o_p.svg
public/icons/svg/filled/blood/blood_rh_n.svg
public/icons/svg/filled/blood/blood_rh_p.svg
public/icons/svg/filled/body/tooth.svg
public/icons/svg/filled/devices/wheelchair_alt.svg
public/icons/svg/filled/diagnostics/hiv_self_test.svg
public/icons/svg/filled/people/call_centre.svg
public/icons/svg/filled/symbols/paved_road_alt.svg
public/icons/svg/filled/symbols/running_water_alt.svg
public/icons/svg/filled/symbols/tally.svg
public/icons/svg/negative/blood/blood_a_n.svg
public/icons/svg/negative/blood/blood_a_p.svg
public/icons/svg/negative/blood/blood_ab_n.svg
public/icons/svg/negative/blood/blood_ab_p.svg
public/icons/svg/negative/blood/blood_b_n.svg
public/icons/svg/negative/blood/blood_b_p.svg
public/icons/svg/negative/blood/blood_o_n.svg
public/icons/svg/negative/blood/blood_o_p.svg
public/icons/svg/negative/blood/blood_rh_n.svg
public/icons/svg/negative/blood/blood_rh_p.svg
public/icons/svg/negative/body/tooth.svg
public/icons/svg/negative/devices/inpatient.svg
public/icons/svg/negative/devices/wheelchair_alt.svg
public/icons/svg/negative/people/call_centre.svg
public/icons/svg/negative/symbols/paved_road.svg
public/icons/svg/negative/symbols/running_water_alt.svg
public/icons/svg/negative/symbols/tally.svg
public/icons/svg/outline/blood/blood_a_n.svg
public/icons/svg/outline/blood/blood_a_p.svg
public/icons/svg/outline/blood/blood_ab_n.svg
public/icons/svg/outline/blood/blood_ab_p.svg
public/icons/svg/outline/blood/blood_b_n.svg
public/icons/svg/outline/blood/blood_b_p.svg
public/icons/svg/outline/blood/blood_o_n.svg
public/icons/svg/outline/blood/blood_o_p.svg
public/icons/svg/outline/blood/blood_rh_n.svg
public/icons/svg/outline/blood/blood_rh_p.svg
public/icons/svg/outline/body/tooth.svg
public/icons/svg/outline/devices/wheelchair_alt.svg
public/icons/svg/outline/people/call_centre.svg
public/icons/svg/outline/people/officer.svg
public/icons/svg/outline/symbols/paved_road_alt.svg
public/icons/svg/outline/symbols/running_water_alt.svg
public/icons/svg/outline/symbols/tally.svg

**Comment by dburka** [comment]
Great List. These are all fixed now in the latest icon PR (which should go live this weekend). Thanks so much @cyberalien 

https://github.com/resolvetosavelives/healthicons/pull/115

**Comment by cyberalien** [comment]
Issue is not completely fixed by that PR:

public/icons/svg/filled/symbols/paved_road_alt.svg is 49 x 49
public/icons/svg/negative/symbols/paved_road.svg is 49 x 49
public/icons/svg/negative/symbols/running_water_alt.svg is 49 x 49
public/icons/svg/outline/symbols/breeding_sites.svg is 49 x 48
public/icons/svg/outline/symbols/paved_road_alt.svg is 49 x 49

White box found in:

public/icons/svg/filled/diagnostics/hiv_self_test.svg
