### ISSUE TITLE
Icon Request: Prevention

### ISSUE THREAD

**Issue by ddbrand** [resolvetosavelives/healthicons#114]
We are a health technology company. Our vision is to empower people to stay healthy for as long as possible. To stay healthy, you don't always need a doctor or medication, you also need exercise - physical and mentally. It would be great to have a set of exercise icons or at least one with weight lifting, as one of the habits of growing old healthily is weight lifting. But also a yoga or similar movements would be super. 

I love your work! It's great! Let's change the world together! 

![Sports](https://user-images.githubusercontent.com/47419456/124129891-83637580-da7e-11eb-9b62-21342dda2b97.png)

**Comment by dburka** [comment]
Great idea. We'll add to the list.

**Comment by dburka** [comment]
I added the following icons to the "to do" list. Need others?
<img width="176" alt="image" src="https://user-images.githubusercontent.com/711809/124347654-9c614900-db9a-11eb-877c-cbd2a5b57437.png">

**Comment by ddbrand** [comment]
**Question: is 'exercise_walk_supported'** a person with a rollator? Like pic attached? 

**Could you also add a person in a wheelchair?** 
I saw that you only have one wheelchair as a device, but for diversity within the people icons it would be great.

<img width="184" alt="Screen Shot 2021-07-05 at 08 48 52" src="https://user-images.githubusercontent.com/47419456/124430323-51e4f580-dd6f-11eb-956b-ebd543155d37.png">
<img width="512" alt="Screen Shot 2021-07-05 at 08 49 54" src="https://user-images.githubusercontent.com/47419456/124430331-54474f80-dd6f-11eb-9503-b6f89b8eda8b.png">

**Comment by ddbrand** [comment]
Within prevention you could also add 
- torso bends
- squats
- stretching

<img width="142" alt="Screen Shot 2021-07-05 at 08 54 09" src="https://user-images.githubusercontent.com/47419456/124430504-88bb0b80-dd6f-11eb-88b9-7e2fd9d9fc18.png">
<img width="94" alt="Screen Shot 2021-07-05 at 08 51 59" src="https://user-images.githubusercontent.com/47419456/124430678-bdc75e00-dd6f-11eb-82e7-5fdfccfcfacb.png">
<img width="317" alt="Screen Shot 2021-07-05 at 08 51 30" src="https://user-images.githubusercontent.com/47419456/124430803-e9e2df00-dd6f-11eb-8138-2cfd217b4673.png">

**Comment by ddbrand** [comment]
And you could add Robotic Personal Training – of course we would love that as we believe that is the future ;)

<img width="883" alt="Screen Shot 2021-07-05 at 09 06 25" src="https://user-images.githubusercontent.com/47419456/124431584-d126f900-dd70-11eb-9c90-1237331f8f3e.png">
<img width="584" alt="Screen Shot 2021-07-05 at 09 09 42" src="https://user-images.githubusercontent.com/47419456/124431599-d71cda00-dd70-11eb-9636-ba3c16bb794c.png">
<img width="505" alt="Screen Shot 2021-07-05 at 09 07 00" src="https://user-images.githubusercontent.com/47419456/124431607-d7b57080-dd70-11eb-9b4e-5e8d4becdde2.png">

**Comment by dburka** [comment]
This is all great. We are adding a person in wheelchair in the next update and also here is the assisted walking one. We'll get to the others too! 
<img width="614" alt="image" src="https://user-images.githubusercontent.com/711809/127740041-1c2228d9-dec9-4581-b29d-d5e2061feb18.png">

**Comment by dburka** [comment]
Do you also want one with a walker-type assisted walking?

**Comment by dburka** [comment]
Weights are coming too. 
<img width="244" alt="image" src="https://user-images.githubusercontent.com/711809/127740068-b37f877c-1862-4aa8-b79f-aa641f3b6547.png">

**Comment by ddbrand** [comment]
Thank you, you are great! I think since more and more people are getting old, it would totally make sense to have that. Also I would not put it within prevention ;)
