### ISSUE TITLE
Website: Add plugins and tools to the /about page

### ISSUE THREAD

**Issue by dburka** [resolvetosavelives/healthicons#116]
There are now several useful tools for Health Icons. Let's add them to the /about page for now.

1. **Figma.** Tekeste's plugin for Figma is almost done. This will be very useful for a lot of people. 
2. **Ruby-on-Rails.** This person Tarelle made a helper to insert icons in Rails apps. https://github.com/tarellel/healthicons
3. **Larevel Template.** @nburka mentioned there was a Larevel template, but I don't know what/where that is.

**Comment by nburka** [comment]
The Laravel template is here https://github.com/troccoli/blade-health-icons
