### ISSUE TITLE
There is no symbol icon named health_alt

### ISSUE THREAD

**Issue by reefle** [resolvetosavelives/healthicons#132]
Hi. health-icons is a great project.
I found this problem while integrating health-icons into mart-emoji-vue.
There is no health_alt in healthicons/public/sitemap.txt either.

![image](https://user-images.githubusercontent.com/83553788/127100216-e7d9b4f0-f48b-4456-9bce-7b1a3ce8c2a0.png)

![image](https://user-images.githubusercontent.com/83553788/127100314-5cc3b403-dabc-409a-bade-0185f9265495.png)

Is health_alt an icon that will be added in the future? 
is it an icon that existed in the past?
is it a typo?

thanks :-)

**Comment by dburka** [comment]
It looks like an icon got misnamed. @nburka Do you know how we should clean this up?

**Comment by dburka** [comment]
This should be fixed.
