### ISSUE TITLE
Start tagging the repo

### ISSUE THREAD

**Issue by troccoli** [resolvetosavelives/healthicons#137]
Hi @nburka ,

as you may remember I have built a [package](https://github.com/troccoli/blade-health-icons) for Laravel developers to use your icons in Blade templates.

I understand this repository is not just about the icon, but about the site as well, but it would be very helpful if you guys would start tagging it. The reason is that so I can tag my package based on your tag, and people will not get confused why an icon is available in your website and not on my package (they could just check the tags).

What do you think?

Giulio

**Comment by dburka** [comment]
Hey @nburka , can we make sure this issue doesn't get lost?
