### ISSUE TITLE
Some icons have incorrect outlines and have background fills

### ISSUE THREAD

**Issue by trafnar** [resolvetosavelives/healthicons#150]
I put the svg "outline" style icons against a dark background and used CSS to override the fill property of the paths, this led me to discover some issues.

I believe icons should look like this (on my dark background with red fill color):
![image](https://user-images.githubusercontent.com/6732/144137577-05594126-fcbc-4034-82b2-a816c4c3cfff.png)

but some look like this, which means they weren't correctly converted to outlines:
![image](https://user-images.githubusercontent.com/6732/144137609-c3be9953-c4b5-4519-8a5e-ad81f0dac07e.png)
![image](https://user-images.githubusercontent.com/6732/144137659-a9be1b40-d374-4ef7-8f40-3b7077c23e20.png)

Several others have white backgrounds in the SVG
![image](https://user-images.githubusercontent.com/6732/144137747-853e952d-f0dd-45b3-9e50-85e725b14a03.png)

Last, these two blister pill icons have some issues:
![image](https://user-images.githubusercontent.com/6732/144137830-cf0f9c65-b1ca-473f-9ae4-9b6a35cdd1d8.png)

I would be happy to fix these but I think it has to happen on the Figma file so that future exports are correct. I've requested access to the file on Figma

**Comment by trafnar** [comment]
One other, this oral contraceptive icon has an issue:
![image](https://user-images.githubusercontent.com/6732/144138070-718a1670-a0ae-47b5-b8c3-a51bc36e27a3.png)

**Comment by trafnar** [comment]
Here's a list of all the icons I've found with issues (I've only checked the 'outline' style)

Misc
- Oral Contraceptive 28 (fill only affects outer edge)
- Blister Pills Round x16 (altering fill color replaces entire icon)
- Blister Pills Round x14 (uses opacity effects)
- Rural Clinic (opacity issue)

Contains non-outlined strokes:
- Exam
- Animal Donkey
- Warning
- Social Distancing
- Activity Run (head is correct, body is not)

has white background shape:
- Wheelchair
- Ventilator
- Quarantine Home
- Calendar Quarantine
- Social Distancing ALT
- Intestinal Pain
- Shield Virus
- Syringe Vaccine
- Virus ALT
- Patient Virus
- Global Pandemic
- Globe
- Chart Cured Decreasing
- Chart Cured Increasing
- Chart Death Rate Decreasing
- Chart Death Rate Increasing
- Chart Death Rate Stable
- Chart Infected Decreasing
- Chart Infected Increasing
- Chart Infected Stable
- Virus Mutation
- Dental Hygiene
- PPE Sanitizer ALT
- Nose
- Loss of Smell
- Viral Lung Infection
- PPE Face Shield ALT
- PPE Virus Sanitizer Spray
- Virus Research ALT
- Virus Research
- Virus Lab Research
- Virus Lab Research ALT
- Liver ALT

**Comment by trafnar** [comment]
I made an app that displays all the SVG icons with customizable fill and stroke colors, this helps to discover icons with problems easily: https://priceless-fermi-4bf406.netlify.app/

**Comment by hawkeye64** [comment]
I found similar, like this one: https://github.com/resolvetosavelives/healthicons/blob/main/public/icons/svg/negative/emotions/nervous.svg

**Comment by hawkeye64** [comment]
This seems to be fixed. I will create a separate ticket for (negative) "nervous" icon (all paths have the same color)

**Comment by trafnar** [comment]
> This seems to be fixed 

When I looked at the Figma file, they seem to be correct there, is that what you mean? Or have they already been updated in the export by someone?

**Comment by hawkeye64** [comment]
The actual files were updated. This issue should be closed (as well as others). Unfortunately, this repo doesn't do releases, so I am using it as a git submodule. Another issue I opened has not yet been fixed: https://github.com/resolvetosavelives/healthicons/issues/151
Unfortunately, it has the wrong tag and I cannot remove it.

**Comment by nburka** [comment]
OMG - this is such an old issue. Sorry everyone! The colors have been normalized for a while, but we've now also updated them to be much easier to override the colors using the `currentColor` CSS feature. We've also removed white backgrounds to make them transparent.

You can now do this:
```
svg {
 background: #123abc;
 color: #abc123;
}
```

Thanks @troccoli for brining it to our attention!
