### ISSUE TITLE
Icon Request: [ALCOHOL]

### ISSUE THREAD

**Issue by ColinCleeren** [resolvetosavelives/healthicons#153]
I run lifestyle programs, as alcohol is an import factor in lifestyle an icon would be very helpful.

**Comment by dburka** [comment]
This is now added. Sorry for the very long wait. :( 

<img width="138" alt="image" src="https://github.com/resolvetosavelives/healthicons/assets/711809/fefd5c44-dcb4-4dbd-a888-6bd19c6d7d57">

**Comment by ColinCleeren** [comment]
Thank you! didn't expected any response anymore. But, it was worth waiting for! still using this awesome icon pack! Have a nice day! greetings, Colin
