### ISSUE TITLE
Icon Request: Emergency Operations Center

### ISSUE THREAD

**Issue by aniciasantos** [resolvetosavelives/healthicons#155]
I would like an icon for an emergency operations center that would typically coordinate an investigation and rapid response after a potentially concerning public health event. This would be used for surveillance information flow diagrams

**Comment by dburka** [comment]
Sorry for the long delay @aniciasantos. Would this be a building with a satellite dish? A person in front of several screens?

![image](https://github.com/resolvetosavelives/healthicons/assets/711809/28bea9bd-23d3-4dcd-ae5f-39ba6450a8b0)

<img width="153" alt="image" src="https://github.com/resolvetosavelives/healthicons/assets/711809/e515eecf-2d9d-4f8b-b742-07e984931d82">

**Comment by aniciasantos** [comment]
Person in front of several screens with something indicating they are looking at "public health events" or reviewing response team updates

**Comment by dburka** [comment]
The icons are pretty small, so compressing in detail like "public health event" is challenging. What about something like this? 
<img width="181" alt="image" src="https://github.com/resolvetosavelives/healthicons/assets/711809/54508eb6-0803-495a-ab24-2f49f2819fda">

**Comment by dburka** [comment]
These were finally added. Thank you for your patience @aniciasantos 
<img width="256" alt="image" src="https://github.com/resolvetosavelives/healthicons/assets/711809/37796997-f09f-4517-b06b-7144b321199a">
