### ISSUE TITLE
Icon Request: [Female Contraceptive]

### ISSUE THREAD

**Issue by JoseGill** [resolvetosavelives/healthicons#158]
**I'm looking for a Female Contraceptive Icon for my website. Have not come across any yet. Will be great if I can get and find one.**

**Comment by dburka** [comment]
We have several female contraceptives in the collection. Is there a specific one you were looking for? Please re-open if you do!
<img width="932" alt="image" src="https://github.com/resolvetosavelives/healthicons/assets/711809/57bced26-1e24-4e56-ac59-a56abf8a36dd">
