### ISSUE TITLE
Icon Request: [reproductive systems]

### ISSUE THREAD

**Issue by cjthecenters** [resolvetosavelives/healthicons#159]
I am looking for icons for sexual health programming, so within the health care scope. Penises, vaginas, anuses. I'm a registered nurse working in HIV prevention.

**Comment by dburka** [comment]
A number of these are added now to our to-do list. Sorry for the very slow response.

**Comment by dburka** [comment]
We now have more of these added. `Anus` is coming soon as well. Thank you for your patience.
<img width="980" alt="image" src="https://github.com/resolvetosavelives/healthicons/assets/711809/29bcc20f-88ef-44c2-ada1-52fd242e2e3d">
