### ISSUE TITLE
Icon Request: [bread]

### ISSUE THREAD

**Issue by lisemari-dignio** [resolvetosavelives/healthicons#160]
Some diseases are sensitive to too much carbohydrates intake. Although we have a nutrition icon in the library today, carrot and apples aren't carb heavy so it doesn't really cover the need for this particular input in our app.
Something in the lines of this would be really helpful:

https://thenounproject.com/icon/bread-4064202/

Thank you!

**Comment by dburka** [comment]
This is added to our list and is being actively worked on. Will be added to the library soon! Thanks for your patience.

**Comment by dburka** [comment]
This was finally added. Thanks for your patience. https://healthicons.org/icon/filled/nutrition/carbohydrates
