### ISSUE TITLE
Icon Request: [pain]

### ISSUE THREAD

**Issue by lisemari-dignio** [resolvetosavelives/healthicons#161]
We have a need to monitor patiens' experienced pain. Chronic pain can be experienced differently, and vary from day to day. We use the 'back pain' icon today, but it would be nice with a more generic pain icon, some suggestions: 

<img width="266" alt="image" src="https://user-images.githubusercontent.com/104753058/166195078-0783bd99-f7c2-41fc-957b-80de94e59c5c.png">

<img width="158" alt="image" src="https://user-images.githubusercontent.com/104753058/166195381-5a115724-30b8-4638-8edc-894487eecaba.png">

**Comment by dburka** [comment]
This is added to the list. Will be released soon. Sorry for the very slow response!

**Comment by dburka** [comment]
This was finally added a few weeks ago. Thank you for your patience. https://healthicons.org/icon/filled/conditions/pain
