### ISSUE TITLE
Icon Request: [blood oxygen]

### ISSUE THREAD

**Issue by lisemari-dignio** [resolvetosavelives/healthicons#162]
Working with remote patient monitoring, patients can measure their blood oxygen level. It would be really nice to have a more blood oxygen icon. Something like this:

device specific: 
<img width="264" alt="image" src="https://user-images.githubusercontent.com/104753058/166195929-a49b1f0c-b0e7-4078-a953-a2494f31a077.png">

or more generic:

<img width="142" alt="image" src="https://user-images.githubusercontent.com/104753058/166195970-7780b053-9753-4988-93d3-c9f6e3f2c4d6.png">

**Comment by dburka** [comment]
Sorry for the long delay. We'll work on this!

**Comment by dburka** [comment]
We just added a Pulse Oximeter icon. Thanks for your patience. 
<img width="241" alt="image" src="https://github.com/resolvetosavelives/healthicons/assets/711809/3c373013-91bd-46be-a852-46d36f95e62b">
