### ISSUE TITLE
Icon Request: Med Search / Pill Pack / Pills

### ISSUE THREAD

**Issue by mtsweir** [resolvetosavelives/healthicons#163]
**Describe the icon you'd like to see and how you would use it.**
Ignore the yellow/grey circles, but these icons would be nice to see added to your library if possible. They would be used like all other icons in your set as well.

<img width="49" alt="Screen Shot 2022-07-01 at 2 21 25 PM" src="https://user-images.githubusercontent.com/4976660/176810844-d4125a6a-2ace-4e05-b56f-a48cb37d9587.png">
<img width="50" alt="Screen Shot 2022-07-01 at 2 15 21 PM" src="https://user-images.githubusercontent.com/4976660/176810280-9bd6adcb-0a30-4869-a4a1-244033e311fc.png">
<img width="118" alt="Screen Shot 2022-07-01 at 2 22 06 PM" src="https://user-images.githubusercontent.com/4976660/176810850-960645c4-28fa-471b-a5ee-bc7dedc382ef.png">

**Comment by dburka** [comment]
We have several combinations of pill packs and combo medicines. Do these suffice? 

<img width="1008" alt="image" src="https://github.com/resolvetosavelives/healthicons/assets/711809/60d4d4cf-dc06-4ce8-b9e6-f1b81d852988">
<img width="447" alt="image" src="https://github.com/resolvetosavelives/healthicons/assets/711809/27b4af0e-78ba-4c7b-a83f-33368a8ddb01">
