### ISSUE TITLE
Icon Request: Medical Samples

### ISSUE THREAD

**Issue by ghost** [resolvetosavelives/healthicons#164]
Hi There

First off this icon set is great, such clean icons.  It really is great, thank you. It also happens to fit perfectly inline with an app I working on.  I would be really appreciative if you could add an icon that represents medical samples, I have looked through the set a bunch of times but none of the existing icons really fit my use case.  I have seen a few online that are nice an clean and would fit with the overall style of the icon set.

![samples-example-01](https://user-images.githubusercontent.com/73957133/179765044-4bc6800b-9954-4ada-8ca6-f4d5f6d883db.png)
![samples-example-02](https://user-images.githubusercontent.com/73957133/179765050-7b1388dd-56a9-44af-be7d-69e20c8c0738.png)
![samples-example-03](https://user-images.githubusercontent.com/73957133/179765052-db672aa7-f057-4489-9a56-e809525fa300.png)

Many thanks

Steven

**Comment by dburka** [comment]
We recently added this to the collection. Thank you for your patience. https://healthicons.org/icon/filled/devices/medical_sample
