### ISSUE TITLE
Interoperability

### ISSUE THREAD

**Issue by antonlytvynenko** [resolvetosavelives/healthicons#165]
Interoperability becomes a big thing in healthcare. Connectivity between the healthcare system is essential for sustainable and cost-effective healthcare. 
It would be nice to see this in a simple icon. Connectivity between silos.

**Comment by timbrisc** [comment]
+1

**Comment by dburka** [comment]
We added this a few weeks ago. Thank you for your patience. https://healthicons.org/icon/filled/symbols/interoperability
