### ISSUE TITLE
Icon Request: Veins

### ISSUE THREAD

**Issue by angie-happytree** [resolvetosavelives/healthicons#166]
I am missing a set of icons concerning the topic veins, blood vessels, varicose veins. Thank you so much!

**Comment by dburka** [comment]
These are now added! 
<img width="258" alt="image" src="https://github.com/resolvetosavelives/healthicons/assets/711809/6ea341f0-b3f6-413f-beff-c759cf82ef2c">

**Comment by dburka** [comment]
Sorry for the slow response!
