### ISSUE TITLE
Icon Request: Sexually Transmitted Diseases icons

### ISSUE THREAD

**Issue by sma49** [resolvetosavelives/healthicons#170]
I could really use some sexual health icons. Gonorrhea, chlamydia and syphilis are three of the most commonly spread STIs in the United States. Syphilis can be represented as a coil. Gonorrhea is a bacteria
![gonorrhea](https://user-images.githubusercontent.com/123771682/215184878-96ae5367-fe1f-4b08-92b0-99fa6abfc698.png)
![syphilis](https://user-images.githubusercontent.com/123771682/215184896-c91388fd-e15f-4486-ad1b-9721c0bf8aa8.JPG)

**Comment by dburka** [comment]
We just added quote a few STI icons! Please let us know if there are more that you would like to see added to the collection.

<img width="715" alt="image" src="https://github.com/user-attachments/assets/005dbe55-e326-4f98-9172-1208bfb0e805" />

**Comment by dburka** [comment]
PS: Thanks for your patience. I know this took a long time.

**Comment by sma49** [comment]
Thanks for the follow up! Much appreciated. A syphilis one (spirochete) would be great too2
________________________________

**Comment by dburka** [comment]
We actually added a Syphilis one at the same time. If you search "STD" on healthicons.org you'll see them all. 
<img width="736" alt="image" src="https://github.com/user-attachments/assets/1c1a6895-d055-49b6-bcc6-9ae51dce3991" />
