### ISSUE TITLE
Icon Request: Sonography

### ISSUE THREAD

**Issue by elgitdejuana** [resolvetosavelives/healthicons#171]
I realized there's a Sonography/Ultrasound icon missing among the "diagnostic imaging" set.
A sonogram is a computer picture of areas inside the body created by high-energy sound waves.
With respect to the icon itself, I think the soundwaves are a must, and the two main elements are the sensor and the screen.
I've seen some icons with a baby in it, but I don't think it's adequate, since you can get a sonogram of almost every organ in the body.
Here are some examples I've found.

Thank you very much for you work. It's very much appreciated.

![image](https://user-images.githubusercontent.com/121913193/225776749-69bc5b0c-1372-47a4-9ee9-a1ab4cf49f44.png)

**Comment by dburka** [comment]
We just added the icon for sonography! 

<img width="166" alt="image" src="https://github.com/resolvetosavelives/healthicons/assets/711809/f47e3dbd-7449-4961-bd7f-c06c5efbeffd">

**Comment by dburka** [comment]
Note: when we do the next release, we will also add a Sonogram icon that doesn't have the background square. 
<img width="245" alt="image" src="https://github.com/resolvetosavelives/healthicons/assets/711809/d648112c-84bc-4df1-afb3-05ce8ff4a890">
