### ISSUE TITLE
Volunteer contributors avatars are broken

### ISSUE THREAD

**Issue by todrobbins** [resolvetosavelives/healthicons#174]
Just noticed the volunteer contributors are not rendering:

![image](https://user-images.githubusercontent.com/158590/226985670-2ad8d0d2-9ca9-4f84-a5c0-50805bef2b44.png)

Looks like the image URLs need to be finessed as they're missing file extensions: `https://unavatar.vercel.app/twitter/superbryntendo`

I'll try and find the relevant code to do a pull request, but wanted to raise the issue here first.

**Comment by nburka** [comment]
Thanks for letting me know! It looks like they changed their URL to https://unavatar.io - which works. They still have annoying caching issues so we often get the generic icon, but at least it's not totally broken anymore.
