### ISSUE TITLE
Icon Request: Mortar and Pestle (compounding)

### ISSUE THREAD

**Issue by kidneywiki** [resolvetosavelives/healthicons#179]
**Request:** A mortar and pestle to symbolize drug compounding.

**Use case:** I am creating a page with pediatric drug dosing guidelines and am in need of icons to symbolize the different formulations of icons. I have tried to make do with emoji but there is an issue. The categories are: 

Tablets/capsules (💊), suspensions (🧪), and extemporaneously prepared (i.e., compounded) solutions (*no suitable emoji available*)

These different formulations have very different implications for patient suitability, access and insurance coverage

**Example:** Here is relatively a clean example of an outline mortar and pestle vector image.

![image](https://user-images.githubusercontent.com/98136061/233502212-3ce8371d-8575-4096-bcca-d58c9ccb9ee5.png)

Thanks for all your work. Big fan of the icon set.

**Comment by dburka** [comment]
This is now done and will go out in the next release in a week or two. 
<img width="654" alt="image" src="https://github.com/resolvetosavelives/healthicons/assets/711809/e366f961-8fd5-4f89-884f-174a8f617c45">

**Comment by dburka** [comment]
Attaching the SVGs in case you need them sooner. Thanks for your patience.
![medicine_mortar_filled](https://github.com/resolvetosavelives/healthicons/assets/711809/aff4fca9-e278-4943-8589-db62cfb1e283)
![medicine_mortar_negative](https://github.com/resolvetosavelives/healthicons/assets/711809/5ec1520e-7767-4ec4-8d65-41d4337023d1)
![medicine_mortar_outline](https://github.com/resolvetosavelives/healthicons/assets/711809/cadc7f30-41ca-4114-8177-3c186e66f6d9)

**Comment by kidneywiki** [comment]
Thank you so much! These are great. I really appreciate your work.
