### ISSUE TITLE
Icon Request: CPR

### ISSUE THREAD

**Issue by seehundnz** [resolvetosavelives/healthicons#182]
Hi all,

it would be nice to have an icon for CPR, like a person performing CPR.

Thank you for your work.

Sebastian

**Comment by SamanvithaAN** [comment]
Hey, thank you for request an icon. We've considered your request and will be working on it soon. Once it's finished, we'll send it to you here so you can download it.

**Comment by dburka** [comment]
This was just added a few weeks ago! Thanks for your patience. https://healthicons.org/icon/filled/people/cpr
