### ISSUE TITLE
Icon Request: [name of icon]

### ISSUE THREAD

**Issue by Chronically-Thriving** [resolvetosavelives/healthicons#183]
I love your icon set, and watching it grow has been awesome. I am a severely chronically ill creator working on making a set of daily management and tracking tools targeted to complex patients like myself. Especially complex patients who are also neurodiverse. One icon I would love to see is an enteral formula carton. You have icons that work for intravenous nutrition, as well as oral nutrition, but as of yet nothing that really fits that “formula,” “shake,” or “smoothie” category. Most enteral formulas come in rectangular cartons with a round spout top for pouring. I’ve attached a rough sketch to just give an idea of what it looks like in my mind’s eye. 

Thank you for the work you are doing!
![IMG_1791](https://github.com/resolvetosavelives/healthicons/assets/134430112/88a48bbe-0fea-4e6e-aaba-8e9c5fed298d)

**Comment by SamanvithaAN** [comment]
Hey! I'm a volunteer at Health Icons, and thank you so much for your kind words. We've considered your icon request and will soon be working on it. Once it's finished, I'll send it to you here so you can download it.

**Comment by dburka** [comment]
We recently added a `Formula` icon. It's technically labeled "Baby Formula" to make it easier to search for but nothing in the  icon is baby-specific. I hope this is useful for you and thank you for your patience. https://healthicons.org/icon/filled/nutrition/baby_formula
