### ISSUE TITLE
Duplicate IDs for Heart icon

### ISSUE THREAD

**Issue by SamKosky** [resolvetosavelives/healthicons#187]
There are two icons with an ID of "heart":
![image (1)](https://github.com/resolvetosavelives/healthicons/assets/12217203/b28d2822-4a10-45ae-80d7-a21339b97b4b)

## body/heart
**Example:** `public/icons/svg/filled/body/heart.svg`

**Metadata**
```
{
  "id": "heart",
  "category": "body",
  "path": "body/heart",
  "tags": [
   "Cardiac",
   "Cardiologist",
   "Cardiology",
   "Coronary",
   "Heart",
   "Organ"
  ],
  "title": "Heart"
 }
```

## symbols/heart
**Example:** `public/icons/svg/filled/symbols/heart.svg`

**Metadata**
```
{
  "id": "heart",
  "category": "symbols",
  "path": "symbols/heart",
  "tags": [
   "Cardiology",
   "Favorite",
   "Like",
   "Love",
   "dhis2:heart"
  ],
  "title": "Heart"
 }
```

The latter overwrites the former, therefore we're never able to use the `body/heart` icon.

## Suggested fix
Update the ID of one of the icons to avoid ID clash.

**Comment by dburka** [comment]
This if fixed in Figma. Will be fixed live the next time we do an export (later this week).
