### ISSUE TITLE
Email Message icon

### ISSUE THREAD

**Issue by mcgilvray-m** [resolvetosavelives/healthicons#189]
We have an online student medical portal and a large portion of our activity is for "secure messaging" between clinicians and patients. We'd like to see a "messaging" SVG icon so that students can choose to enter our secure message portal.

**Comment by SamanvithaAN** [comment]
Hey, I'm a volunteer at Healthicons. We'd like to understand your request a bit more. 
Can you help us understand how you are keeping the messaging portal 'secure'? 
Do they enter a chat screen when they enter this portal?

**Comment by mcgilvray-m** [comment]
Our patients are required to login via two factor authentication and the
email they send/receive is only viewable on the portal (encrypted HTTPS) by
the patient and in our medical records system (encrypted at rest in the
database) by our medical providers.

Is it not very common to have mail messaging between patient and provider
on all patient portals? I have it with my doctor.  Samanvitha don’t you? No
offense meant, please.

More than 30% of our healthcare is completed through asynchronous care
which is done primarily through secure messaging.  This will grow to over
50% in the coming year.

Thank you for your consideration!

**Comment by mcgilvray-m** [comment]
Thanks Daniel!
