### ISSUE TITLE
Icon Request: Symptoms, Heart, Orthopedics, Eye, Nerve, Allergies, Lungs, Liver, Women, Test tube, CT Scan, Human Resources

### ISSUE THREAD

**Issue by Micron-Kaho** [resolvetosavelives/healthicons#190]
**Describe the icon you'd like to see and how you would use it.**
We'd like to use your wonderful icon in our website to describe our experiences for each item. We are not requesting to create the new ones. 
- Symptoms
- Heart
- Orthopedics
- Eye
- Nerve
- Allergies
- Lungs
- Liver
- Women
- Test tube
- CT Scan
- Human Resources

Thank you for your attention.

Best Regards,
Kaho

**Comment by dburka** [comment]
You are more than welcome to use all of these icons @Micron-Kaho! Is there anything you need from us or are you just letting us know that you plan to use the icons?

**Comment by Micron-Kaho** [comment]
Since the icons are so nice, we'd like to use it more on the website https://micron-kobe.com/en and also on the sales materials and documents. Please let us know if it's out of scope, and we shouldn't use.

Also sorry for the lables for "Request". We're just letting you know in advance.

Wish you a nice day.

**Comment by dburka** [comment]
Yes, you can use the icons on your website. They are free to use for any
type of project. Thank you.

**Comment by dburka** [comment]
You can use them on your sales materials and documents also. Thank you.
