### ISSUE TITLE
Meta Data import issue

### ISSUE THREAD

**Issue by sgarrity** [resolvetosavelives/healthicons#191]
It looks like the https://github.com/resolvetosavelives/healthicons/blob/main/public/icons/meta-data.json file is empty after [5b3aeb5](https://github.com/resolvetosavelives/healthicons/commit/5b3aeb5bc18db595e753f28735af0ff9a506bb0a).

Not sure why yet, but it is resulting in the tags being missing from the icon details, and the filename being used in place of the Title.

**Comment by sgarrity** [comment]
I figured it out (and fixed it for now).

@dburka When the Figma page was renamed from `Export` to `Export (Be Careful)`, the import script broke.

I've renamed the page back to `Export`. It should be a trivial change for a dev to gracefully ignore the ` (Be Careful)` part of the page title.

**Comment by sgarrity** [comment]
How do we force the live site to rebuild based on the Figma file?

**Comment by sgarrity** [comment]
> How do we force the live site to rebuild based on the Figma file?

Got it. Live site is fixed, but I'll leave this issue open until we make the import script a bit more robust.

**Comment by dburka** [comment]
Thanks. Sorry, I'm the one who renamed the page (obviously not realizing there were downstream consequences). Sorry!

**Comment by sgarrity** [comment]
A @dburka noted on Slack: _"I think it's ok that this is a little fragile."_
