### ISSUE TITLE
How do i import in my React Project

### ISSUE THREAD

**Issue by izzabellerina** [resolvetosavelives/healthicons#197]
So sorry that i can't find the way to import to the project.
Can u explain how to import it from filename like blood_b_n to the react project.

Thank you in advance

**Comment by nburka** [comment]
@izzabellerina I will respond later today, or tomorrow with some sample code.

**Comment by izzabellerina** [comment]
@nburka 
Thank you in advance , and i found the solution but the problem is that I set the color = red and then the icon didn't change for me 
`<BloodBag color="red" height={36} width={36} />
`
I found solution from this website 
[https://www.npmjs.com/package/healthicons-react](url)

Thank you again

**Comment by nburka** [comment]
Nice! I didn't even see your response here before I tried it myself. It is super easy. All I did was:
1. create a sample React app using `create-react-app`
2. add the NPM package for the icons using: `npm i healthicons`
3. edited the `App.js` and added `import { ReactComponent as HeartIcon} from 'healthicons/public/icons/svg/filled/body/heart_organ.svg';` and then used the icon by adding: `<HeartIcon color="red" height={100} width={100} />`

Glad it worked for you!!

**Comment by nburka** [comment]
It looked like this:

![Screenshot 2024-04-04 at 4 52 37 PM](https://github.com/resolvetosavelives/healthicons/assets/1284966/3586d245-430f-4f5b-8cbe-7a49cb5c1f91)

**Comment by nburka** [comment]
I'll close this issue. But let me know if you have any more questions.
