### ISSUE TITLE
Icon Request: Life Sciences and BioPharma Icon set

### ISSUE THREAD

**Issue by SamuelWoodard** [resolvetosavelives/healthicons#199]
Icons used for Life Sciences and biopharma and Healthcare IT

**Comment by timbrisc** [comment]
+1 anything Health IT

**Comment by timbrisc** [comment]
I work in the health data standards space so I'd love to see icons for code systems like (ICD, LOINC, SNOMED CT, etc.) just as there already is one for HL7 FHIR. 

I have worked in the past for [OpenHIE](https://ohie.org) (Open Health Information Exchange). The provide a framework for ministries of health to adopt with the goal of interoperability.  You can read more about their components on their site. They also have a [diagram](https://ohie.org/diagram) which helps to visualize the different parts of an ideal HIE system. It would be great to see those pieces as icons in this repository as they are the building blocks of Health IT.

**Comment by SamanvithaAN** [comment]
Hey, thanks for being patient with us. As of now, we've published these icons: 
- ICD
- ICD 11
- ICD 10
- ICD 9
- LOINC
- QR Code

**Comment by dburka** [comment]
We just published Life Sciences as well as Biomarker and Biopharma.
<img width="220" alt="image" src="https://github.com/user-attachments/assets/b3e0c9f8-85b7-4e54-a9c7-c7e98b6eeb47" />
<img width="116" alt="image" src="https://github.com/user-attachments/assets/3879e1d6-2c9b-4dc0-898e-971ae664c4c7" />
