### ISSUE TITLE
Icon Request: Anthropometric data (weight, stature, lenght, body mass index, cephalic perimeter)

### ISSUE THREAD

**Issue by joaocolaco** [resolvetosavelives/healthicons#201]
Hi all.
Great work!
It could be usefull to have icons to visually represent anthropometric measurements like weight, stature, lenght, body mass index, cephalic perimeter, etc.

Examples 
- weight: Scale or a person on a scale
- stature/lenght: a prone baby being measured 8in the horizontal)
- height: a person being measured, 
- body mass index: trickier, maybe a combination of the height and weight icon?
- head circumference: a ruler measuring the perimeter of the head (of a baby?)
- arm circumference: a ruler measuring the perimeter of the arm

More information about those measurements in https://www.who.int/tools/child-growth-standards, https://www.who.int/tools/growth-reference-data-for-5to19-years or https://www.cdc.gov/growthcharts/clinical_charts.htm.

Best regards,
João Colaço

**Comment by dburka** [comment]
Thank you so much for your request. We will add these to the list. Please be patient as our volunteer team isn't super fast :)

**Comment by joaocolaco** [comment]
> Thank you so much for your request. We will add these to the list. Please be patient as our volunteer team isn't super fast :)

No problem, it's understandable.

**Comment by SamanvithaAN** [comment]
Hey, your request has been added to the list. However, we already have an icon for weighing scale. Please have a look: https://healthicons.org/icon/filled/devices/weight

**Comment by SamanvithaAN** [comment]
Hey, 
Please find the below icons you requested on Heath icons! 
- Weight 
- Height
- Waist Circumference
- Head Circumference
- Head
- BMI
- Arm Circumference

**Comment by joaocolaco** [comment]
> Hey, your request has been added to the list. However, we already have an icon for weighing scale. Please have a look: https://healthicons.org/icon/filled/devices/weight

Thanks. I’ve missed that one.

**Comment by joaocolaco** [comment]
Just one thing. The BMI icon in https://github.com/resolvetosavelives/healthicons/blob/main/public/icons/svg/filled/symbols/body_mass_index.svg seems to be glitchy at least on a mac. Can you check it?

Thanks.

**Comment by joaocolaco** [comment]
Ok, after, the commit 92a775ee5a15015a44fdbd8dc8da43cc727a42d6 were icons were introduced, the 88b634effe0a31a5a78770c264ef2d8835625833 seems to have fixed the glitch. 
I will close the issue.

**Comment by dburka** [comment]
Great. Thanks João
