### ISSUE TITLE
Icon Request: Diffrent types of cancers

### ISSUE THREAD

**Issue by shradheyagupta** [resolvetosavelives/healthicons#203]
I primarily focus on breast cancer research. When I searched for icon of breast, I couldn't find any. Then I seached with a keyword 'cancer' then two icons appeared, one of cervical cancer and other of oncology.

I'm seeking a collection of icons similar to those for cervical cancer representing breast, prostate, lungs, blood, colon, and various other cancers. 

Instead of ribbon abnormal cells will be more relevant.

**Comment by dburka** [comment]
Great request. Yes, we can work on these. Please be patient with us!

**Comment by SamanvithaAN** [comment]
Hey, thanks for being patient. As of now, we've published the following icons:  
- Pancreatic Cancer
- Prostate Cancer
- Stomach Cancer
- Cell Nuclei Cancerous

**Comment by dburka** [comment]
We've added many types of cancers now. Please open a new request if you see cancers that we haven't yet included. Thanks for your patience and your request!

<img width="475" alt="image" src="https://github.com/user-attachments/assets/b1223f2f-51af-4052-9cc8-53f215438831" />
<img width="456" alt="image" src="https://github.com/user-attachments/assets/6466566e-e691-4fe8-98bd-4fc8d2a8b8e4" />
<img width="492" alt="image" src="https://github.com/user-attachments/assets/cb8701a2-cef9-40a3-8657-c01832608309" />
