### ISSUE TITLE
Icon Request: Breast outline (for breast cancer)

### ISSUE THREAD

**Issue by User-nail-slaw-bulk** [resolvetosavelives/healthicons#208]
Hi, could you please create a minimalist, stylized side view outline of a female breast for breast cancer awareness materials. The current design uses a single, continuous curved line to suggest the breast's shape. It starts with a vertical line for the chest, then curves outward and back inward to form the breast contour, ending with a small curve to hint at the nipple. The icon should be simple, abstract, and appropriate for medical education purposes. Aim for a clean, professional look that's recognizable but not overly detailed or anatomically explicit

See example attached. Thank you for your help and work on this matter. It's much appreciated. 

![breast](https://github.com/resolvetosavelives/healthicons/assets/174580226/5c22e9cf-2f28-4951-82b5-d6ca3079eeb9)

**Comment by SamanvithaAN** [comment]
Hi,
Thank you for your icon request. We will begin working on it soon. As we are a volunteer-led team, we appreciate your patience. We will notify you once it is published.

**Comment by dburka** [comment]
We have breast, breast cancer, and breastfeeding now as icons!
<img width="375" alt="image" src="https://github.com/user-attachments/assets/5f9b5319-c2c9-474f-8f83-0cead1f8b99a" />
