### ISSUE TITLE
Icon Request: [genders]

### ISSUE THREAD

**Issue by antonsten** [resolvetosavelives/healthicons#210]
Hi, 

Would be great to get gender icons (separated) - right now there only seems to be the combined version. Thanks!

**Comment by SamanvithaAN** [comment]
Hey, the female symbol and male symbol has been added to our collection. Please find them here. Thank you for request and patience.
https://healthicons.org/icon/filled/symbols/female
https://healthicons.org/icon/outline/symbols/male
