### ISSUE TITLE
Icon Request: Prescription Alt

### ISSUE THREAD

**Issue by edugarciagodoy** [resolvetosavelives/healthicons#220]
**Describe the icon you'd like to see and how you would use it.**

**Comment by dburka** [comment]
Hi @edugarciagodoy! Are you looking for a new icon or are you asking permission to use `prescription_alt`? You can use any of the icons for anything that you want.
<img width="160" alt="image" src="https://github.com/user-attachments/assets/0086d979-910e-42ab-a975-f784d83a52d9">
