### ISSUE TITLE
Icon Request: [staples and stitches]

### ISSUE THREAD

**Issue by mhamoudaucsd** [resolvetosavelives/healthicons#225]
**Describe the icon you'd like to see and how you would use it.**
I want an icon of sutures and another icon for skin stapling that look like the pics attached.
Will be using it in my visual abstract to publish it in a journal
Thanks!

![Z6DJIEXbkxNhUGzQTlPi](https://github.com/user-attachments/assets/4aef61b9-8ac5-48f6-9ac1-fbe29a28aea8)

**Comment by dburka** [comment]
These just went live. Thanks for the request.
<img width="263" alt="image" src="https://github.com/user-attachments/assets/7eb2f100-c6d2-4cd0-ac0a-5e7f55fc0a25" />
