### ISSUE TITLE
Icon Request: [dry mouth]

### ISSUE THREAD

**Issue by potockawiktoria** [resolvetosavelives/healthicons#228]
**Describe the icon you'd like to see and how you would use it.**
Hello,

I would like to ask to create a new icon representing dry mouth. It is often drawn by showing a cracked up tongue coming out of open mouth, something like below:

https://img.freepik.com/premium-vector/dry-mouth-icon-vector-image-can-be-used-allergy-symptoms_120816-81821.jpg
https://www.shutterstock.com/image-vector/diabetes-symptom-dry-mouth-line-600nw-2434075757.jpg
https://i-cf65.ch-static.com/content/dam/cf-consumer-healthcare/health-professionals/en_IN/icons/GEP343_Candidosis_Icon.png?auto=format

Thank you!
Wiktoria :)

**Comment by dburka** [comment]
This icon was just released! Thanks for the request.
<img width="152" alt="image" src="https://github.com/user-attachments/assets/68b44739-e971-4695-ae13-437052190905" />
