### ISSUE TITLE
Icon Request: [dry eyes]

### ISSUE THREAD

**Issue by potockawiktoria** [resolvetosavelives/healthicons#229]
**Describe the icon you'd like to see and how you would use it.**
Hello,

I would like to ask to create a new icon representing dry eyes. It is often drawn by showing a lines in the eye, something like below:
https://cdn3.iconfinder.com/data/icons/eye-surgery/1000/Eye-10-512.png
https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS7T3sXDgcC851JYihvbIdgmZNcoIpL-mBW7Q&s
https://c8.alamy.com/comp/2H26R4J/isolated-on-white-backgroundline-art-vector-illustration-2H26R4J.jpg
https://media.istockphoto.com/id/1310400998/vector/eye-sore-line-and-glyph-icon-disease-and-allergy-eye-redness-vector-icon-vector-graphics.jpg?s=612x612&w=0&k=20&c=0c_ivx4Cpk8njWqJXRm3s249BsyvlLM92Z9kAKuDELw=

Thank you!
Wiktoria :)

**Comment by dburka** [comment]
This icon just went live in the collection! 
<img width="114" alt="image" src="https://github.com/user-attachments/assets/e29eb11a-a57b-4b26-a94a-20777f11693e" />
