### ISSUE TITLE
Basic icon organization proposal

### ISSUE THREAD

**Issue by sgarrity** [resolvetosavelives/healthicons#4]
This is a summary of a discussion in Slack on how to organize icons (in Figma, and in exports). Comments and feedback are encouraged. If, once reviewed/updated, this proposal is accepted, I can create a PR to add it to the README file.

---

### Category
Each icon must belong to a single category (People, Devices,  Diagnostics, etc.).

The category should be included preceding a forward slash character in the Figma layer name. For example: `People/doctor_female_outline`

### Description
The description should include a brief description of the icon. For example, the description of the `doctor_female` icon could be: _"Woman with stethescope"_.

The description should be stored as the Description field for components in Figma.

### Tags
Each icon can have multiple tags intended to help people search for an discover icon. Tags can include alternate or related terms for the icon (for example "doctor" and "physician").

Tags are stored along with the description in the Description field for components in Figma in a comma-delimited list inside square brackets. For example: `Description... [tag 1, tag 2, tag 3]`

### Variations
Each icon is available in a positive, negative, and outline variation. these variations should be indicated with a trailing underscore character and the name of the variation. For example, `doctor_female_positive`, `doctor_female_negative`, and  `doctor_female_outline`.

**Comment by dburka** [comment]
This this issue still relevant @sgarrity? There is certainly room for someone to reorganize the whole set and come up with a more robust taxonomy (a lot of icons fall under "People" or "Symbol" pretty arbitrarily right now).

**Comment by sgarrity** [comment]
We can close this. The organization send to be working fine.

**Comment by dburka** [comment]
This is closed.
