### ISSUE TITLE
Feature: Figma API integration

### ISSUE THREAD

**Issue by nburka** [resolvetosavelives/healthicons#50]
We'd love to be able to:
 - pull meta data about each icon stored in Figma
 - possibly export all of the icons and save them in our dir structure + make a ZIP file

Ideally it would run with `yarn update-figma-icons` or something like that.

There are two options:
 1. Make a custom Figma plugin. I've never done this, so I'm not sure how much work it would be.
 2. Use the `description` field and import that. Steven has already proposed a syntax for this second approach (seems like the easier approach)
 
[See Slack conversation](https://healthicons.slack.com/archives/C023E17F4AG/p1622136266060400)
 > I would suggest that we use that Description field for a verbal description of the icon (like alt text, eg. “Person with lab coat and stethoscope”), and a comma-delimited list of tags in square brackets. So, a description of the `doctor_female` icon would be something like: `Woman with stethoscope [doctor, physician, woman, practitioner]`

**Comment by nburka** [comment]
See API documentation https://www.figma.com/plugin-docs/api/ComponentNode/#description

**Comment by dburka** [comment]
Note: We should create a tag like `dhis2:file_name` for every icon that represents a DHIS2 icon. Then we can change the actual filename to be consistent, use hyphens, and be meaningful

**Comment by nburka** [comment]
I've got a start of this working.

**Comment by nburka** [comment]
I'm using the https://www.npmjs.com/package/figma-js package, but this might be even better? I'm not that familiar with GraphQL thugh https://github.com/braposo/figma-graphql
