### ISSUE TITLE
Icon Request: Crutch

### ISSUE THREAD

**Issue by nburka** [resolvetosavelives/healthicons#52]
Another basic health icon

<img width="281" alt="Screen Shot 2021-05-31 at 9 35 06 PM" src="https://user-images.githubusercontent.com/1284966/120254547-162eab80-c258-11eb-9379-2297ae2fe95a.png">

**Comment by nburka** [comment]
This has been added to Figma

**Comment by dburka** [comment]
This is now in the collection
