### ISSUE TITLE
Documentation: Add instructions for updating the icons on the website to README.md

### ISSUE THREAD

**Issue by nburka** [resolvetosavelives/healthicons#59]
The instructions are something like:

1. export from Figma (this is the part I don’t know much about)
2. make a zip file of all of the icons
2. make a branch `git checkout -b icon-update-june-1-2022 upstream/main`
3. save the icons over the public/icons files
4. commit the change `git commit -m "icon update June 1 2022" public/icons/`
5. push to gitub `git push origin icon-update-june-1-2022`
6. make a PR
7. get someone to review the PR and merge it

We might even be able to make steps 2-5 automated using `yarn prep-icons path/to/icons` or something. That said, maybe all of this will just be replaced by the API task, if that's possible? See  https://github.com/resolvetosavelives/healthicons/issues/50

**Comment by dburka** [comment]
This is done, I think.
