### ISSUE TITLE
Icon Request: Bandage

### ISSUE THREAD

**Issue by nburka** [resolvetosavelives/healthicons#60]
Another basic medical icon. A bunch of good examples here https://thenounproject.com/term/medical-plaster/
<img width="368" alt="Screen Shot 2021-06-01 at 8 18 25 AM" src="https://user-images.githubusercontent.com/1284966/120322011-f4faa900-c2b1-11eb-9f2a-1108b5b682f5.png">

**Comment by nburka** [comment]
Maybe also "head bandage"?

<img width="175" alt="Screen Shot 2021-06-01 at 8 34 01 AM" src="https://user-images.githubusercontent.com/1284966/120324072-30967280-c2b4-11eb-9749-4ddda6fbd489.png">

**Comment by nburka** [comment]
this is already in Figma under "band_aid"

**Comment by dburka** [comment]
This will be live soon.
