### ISSUE TITLE
Icon Request: Cast/Sling

### ISSUE THREAD

**Issue by nburka** [resolvetosavelives/healthicons#62]
We could have variations on this one:

"Arm in Cast"

<img width="181" alt="Screen Shot 2021-06-01 at 8 19 43 AM" src="https://user-images.githubusercontent.com/1284966/120322189-24a9b100-c2b2-11eb-9c9e-95b130c4373d.png">

"Hand in Cast"

<img width="419" alt="Screen Shot 2021-06-01 at 8 20 26 AM" src="https://user-images.githubusercontent.com/1284966/120322407-60dd1180-c2b2-11eb-9988-2d0110664031.png">

"Arm in Sling"

<img width="453" alt="Screen Shot 2021-06-01 at 8 21 45 AM" src="https://user-images.githubusercontent.com/1284966/120322465-6f2b2d80-c2b2-11eb-9241-da83734b7047.png">

**Comment by dburka** [comment]
I've added these to NEW ICONS and started working on them. They'll get finished soon.
