### ISSUE TITLE
Icon Request: Medical Chart

### ISSUE THREAD

**Issue by nburka** [resolvetosavelives/healthicons#64]
We have "documents",  but something like this:

<img width="463" alt="Screen Shot 2021-06-01 at 8 35 34 AM" src="https://user-images.githubusercontent.com/1284966/120324206-5cb1f380-c2b4-11eb-9766-f1d58aad771a.png">

<img width="365" alt="Screen Shot 2021-06-01 at 8 35 28 AM" src="https://user-images.githubusercontent.com/1284966/120324210-5e7bb700-c2b4-11eb-9b64-1e321a224919.png">

**Comment by dburka** [comment]
This is now on the site
