### ISSUE TITLE
Icon Request: Pulse Oximeter

### ISSUE THREAD

**Issue by njdelaney** [resolvetosavelives/healthicons#92]
These images are great! We have been supporting home oximetry services where people are sent a pulse oximeter at home to measure their oxygen levels and get help quickly. A pulse oximeter icon on a finger would be super. This is an example of an image https://www.nytimes.com/2020/04/24/well/live/coronavirus-pulse-oximeter-oxygen.html but a box on a finger maybe with 98 in the box or SpO2 e.g. an icon image similar to step 4 in our animated video https://youtu.be/ifnYjD4IKus?t=93 many thanks!

**Comment by dburka** [comment]
Great suggestion! We'll add it to the list.

**Comment by dburka** [comment]
How do these look @njdelaney ? 
<img width="800" alt="image" src="https://user-images.githubusercontent.com/711809/122638439-f1846180-d0a8-11eb-9b3a-671ac22826d4.png">

**Comment by dburka** [comment]
This is now in the set.

**Comment by njdelaney** [comment]
I'm sorry for the delay in replying I have been on leave -- these look amazing, thank you!
