### ISSUE TITLE
Icon Request: IV

### ISSUE THREAD

**Issue by fokked** [resolvetosavelives/healthicons#94]
I'm working with a pharmacist to display dosages in a chart. They want to communicate the route of administration.

You could modify the blood type bags and repurpose them for IV.

Thanks,
Kristen

**Comment by dburka** [comment]
Can you explain how you'd design this? Is it just a blood bag without letters, so it's a generic liquid? Or do you need to see the needle at the end? A few examples below. 
<img width="251" alt="image" src="https://user-images.githubusercontent.com/711809/121772198-cdfd6c00-cb28-11eb-8b8b-1e91d71ae886.png">

![image](https://user-images.githubusercontent.com/711809/121772192-c3db6d80-cb28-11eb-8232-7d6bec3a6b50.png)

**Comment by sgarrity** [comment]
Maybe it's just as a non-medical professional who watches too much TV, but I associate the mounting rack/structure with IV, like the one in the existing hospital-bed icon:

<img width="235" alt="image" src="https://user-images.githubusercontent.com/58062/121775548-ca84d780-cb5e-11eb-98fd-f1144ff74fdf.png">

**Comment by nburka** [comment]
For our context, and I think it makes sense for the icon, we need just an "IV bag". It's to differentiate between the different way drugs are administered: pill, needle, IV. So the blood bag without letters is good. Only other suggestion would be to maybe add horizontal measurement markers.

![iv-bag-2353991-1960197](https://user-images.githubusercontent.com/1284966/121913578-854bdb80-ccff-11eb-811c-c1accdf1c0e1.png)

![162257-200](https://user-images.githubusercontent.com/1284966/121913606-8a108f80-ccff-11eb-887c-49081aed42d0.png)

**Comment by nburka** [comment]
For Steven's "bed" example, that could be "IV and Hospital Bed" or something - but a different icon nonetheless. Let's ignore that until someone requests it.

**Comment by dburka** [comment]
How is this @fokked @nburka ? 
<img width="237" alt="image" src="https://user-images.githubusercontent.com/711809/122064690-3016d500-cda6-11eb-926f-1c28b264c636.png">

**Comment by dburka** [comment]
We ended up with something closer to the blood bag. 
<img width="524" alt="image" src="https://user-images.githubusercontent.com/711809/122637356-0231d900-d0a3-11eb-8818-e86e703c319f.png">

**Comment by nburka** [comment]
@dburka Looks awesome. Should I close the issue?
