### ISSUE TITLE
therapy icons 

### ISSUE THREAD

**Issue by eleary4** [resolvetosavelives/healthicons#95]
would be great to have icons for various therapies / clinics (e.g. physical therapy, occupational therapy, speech therapy, vision clinic, urology clinic, etc). i'm looking to put these icons on signage around the hospital for those with literacy challenges. Let me know what you think!

**Comment by dburka** [comment]
Great idea. A Canadian doctor friend of mine created this list below that we're going to work on. Do you see any that are missing? 

<img width="226" alt="image" src="https://user-images.githubusercontent.com/711809/121772296-6267ce80-cb29-11eb-8320-20ceebf49dcb.png">
<img width="231" alt="image" src="https://user-images.githubusercontent.com/711809/121772302-6ac00980-cb29-11eb-96ae-1336d5dcff33.png">
<img width="213" alt="image" src="https://user-images.githubusercontent.com/711809/121772306-74e20800-cb29-11eb-8d90-b85c2f1a4261.png">

**Comment by dburka** [comment]
We just pushed a bunch of these live @davidpearl to healthicons.org under the subheading SPECIALTIES @eleary4
