### ISSUE TITLE
Icon Request: Health Literacy

### ISSUE THREAD

**Issue by davidpearl** [resolvetosavelives/healthicons#97]
**Describe the icon you'd like to see and how you would use it.**
Hi there, 

I work in the Health communication field and would love to see an icon for "Health Literacy". 

Thanks,
David

**Comment by dburka** [comment]
Great suggestion @davidpearl. Are you thinking just a book with a health/cross icon on it? Or is there a better representation that you can think of? Thanks!

**Comment by dburka** [comment]
Something like this @davidpearl ? 
<img width="151" alt="image" src="https://user-images.githubusercontent.com/711809/122670006-a041a400-d174-11eb-996d-781a3bb917fe.png">

**Comment by nburka** [comment]
I like the icon. First impression: looks like a "+" and a bendy "-". Have you tried with just the cross on the right-hand side?

**Comment by dburka** [comment]
We just pushed this live @davidpearl to healthicons.org
