### ISSUE TITLE
Icon filename on README

### ISSUE THREAD

**Issue by troccoli** [resolvetosavelives/healthicons#98]
Hello,

I have created a package to be able to use your icons in Blade template in Laravel. There are plenty of this kind of packages to use all sorts of icons. Have a look at [https://github.com/blade-ui-kit/blade-icons#icon-packages](https://github.com/blade-ui-kit/blade-icons#icon-packages).

My package is [here](https://github.com/troccoli/blade-health-icons) and as you can see, I instruct the user to click on the icon they want on your website and note the `dhis2` tag to find out what name they should use. I understand not all icon have a `dhis2` tag, so here's my question.

Would it be possible to add the icon filename, e.g. `blood_a_n`, to the icons in the README? Maybe as a tooltip?

**Comment by nburka** [comment]
Troccoli, good question. Probably using the DHIS2 icon name isn't necessary, right? You just need a way for a person to find the icon, and then the icon filename the icon? We could show the directly in the modal. So something like:

<img width="786" alt="Screen Shot 2021-06-26 at 4 53 40 PM" src="https://user-images.githubusercontent.com/1284966/123525492-14150c80-d69f-11eb-8f32-be6b45fbbdec.png">

**Comment by nburka** [comment]
@troccoli would that do what you need? Could be useful for others looking for the file in the dir structure if they download the ZIP file too.

**Comment by nburka** [comment]
In case it's useful for you in the future, there's also a JSON representation of all of the icons here healthicons.org/icons/meta-data.json

**Comment by troccoli** [comment]
Sorry for late reply. The filename in the modal would be perfect @nburka . Thanks

**Comment by nburka** [comment]
@troccoli done! It's live now. Can I close this issue?

**Comment by troccoli** [comment]
Of course. Thank you very much

**Comment by nburka** [comment]
Thank you! It's cool to see that Blade template.
