### ISSUE TITLE
Icon Request: Micronutrients

### ISSUE THREAD

**Issue by KevinBeckers** [resolvetosavelives/healthicons#99]
**Describe the icon you'd like to see and how you would use it.**
[Micronutrients](https://en.wikipedia.org/wiki/List_of_macronutrients) like fat, protein and carbohydrates would be useful to indicate the contents of food.

**Comment by dburka** [comment]
Good suggestion. Do you have any examples @KevinBeckers that would help us? I did a quick google images search and it's not obvious how to represent `micronutrients`

**Comment by KevinBeckers** [comment]
Hi, this is a hard question because, usually you need some knowledge to understand the meaning. As far as I know these are the way people represent them:

- Carbs (energie, speedometer, grain)
- Protein (twisted ribbon, muscle, egg)
- Fat (droplet, human fat cell, avocado)
- Alcohol (beer bottle, human liver)
- Vitamines (capsule, orange)
- Minerals (mineral stone, diamond)

Most of the time existing sets are inconstant or incomplete.
